name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Novidades'
    label: 'feature'
  - title: '🛠 Manutenção'
    label: 'chore'
  - title: '🐛 Bug Fixes'
    label: 'fix'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'maintenance'
      - 'bug'
  default: patch
replacers:
  - search: '/([A-Z]{2,5}-\d{1,6})/g'
    replace: '[$1](https://imakecodes.atlassian.net/browse/$1)'
autolabeler:
  - label: 'maintenance'
    title:
      - '/^chore.+/i'
  - label: 'bug'
    title:
      - '/^fix.+/i'
  - label: 'feature'
    title:
      - '/^feat.+/i'
  - label: 'major'
    title:
      - '/^[a-zA-Z]+(\(.*?\))?!:.+/i'
template: |
  ## O que tem de novo
  $CHANGES
