# Generated by Django 3.1.3 on 2020-11-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20201105_0303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="Staff?"),
        ),
    ]
