# Generated by Django 3.1.3 on 2020-11-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_auto_20201106_2357"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameevent", old_name="event_col", new_name="col",
        ),
        migrations.RenameField(
            model_name="gameevent", old_name="event_row", new_name="row",
        ),
    ]
