# Generated by Django 3.1.3 on 2020-11-07 01:30

from django.db import migrations
import django_mysql.models
import internal.utils


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_auto_20201107_0010"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="board_progress",
            field=django_mysql.models.JSONField(
                default=internal.utils.empty_list,
                help_text="This board is updated at each GameEvent recorded",
                verbose_name="Progress board",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="board",
            field=django_mysql.models.JSONField(
                default=internal.utils.empty_list,
                help_text="The generated board game",
                verbose_name="Generated board",
            ),
        ),
    ]
