name: Creates a docker image for production

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Build & Push to GitHub Package
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.NEXUS_USERNAME }}
          PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          REGISTRY: "docker.nexus.makecodes.dev"
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "mines-backend"
          TAG_NAME: "main"
          LATEST: "true"
